### ISSUE TITLE
Out of Class Work : Agile Terms

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team2#1]
@katenamgayoung, @bhavanisp

Here is a key list of Agile terms clustered into groupings. Please familiarize yourselves with these terms as we will be using them frequently in class. 

https://github.com/IDX-597-05/Course-Information/wiki/C.-Agile-Terminologies

GitHub project management: a guide
https://www.zenhub.com/github-project-management
Review the difference between Agile Term and GitHub Term and ZenHub terms and relationships to GitHub

**Comment by akallish** [comment]
Hello @katenamgayoung, @bhavanisp

Good Morning.

What is the status of this task?

- Remember any team member can move this task from "new issue" to "in progress" on the team kanban. 
- You also create a check box list if a team member has completed a task (besides having conversations about the task) like below:

- [ ] Gayoung Nam 
- [ ] Bhavani Shivaram Prasad 
- [ ] Rutuja Chavan Vasant

You can also have conversations, add links, and add images to an issue to help complete a task.

**Comment by bhavanisp** [comment]
@katenamgayoung Please let me know if you are able to view Zenhub now.

**Comment by akallish** [comment]
> Please let me know if you are able to view Zenhub now.

@katenamgayoung I reinvited you to ZenHub just in case. If you can get into this repository, can you click on the ZenHub tab and does it load and you can see the issues in the Kanban?
