### ISSUE TITLE
Out of Class Work : Who we are as a team?

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team2#2]
@katenamgayoung, @bhavanisp

This is an important exercise for new teams to understand the facts and motivations about individual contributors (talent density) and then discuss how they can go from a group of individual contributors to an interdependent team over time. 

Team 1
https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1694035378749/4d1b5d1ec86e05550714642152084635b93b6423?sender=u8174af0a23de37cd1e842670

Team 2
https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1694035417903/972986af5d82d54a058cc630895b4fc373eb009d?sender=u8174af0a23de37cd1e842670

Team 3
https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1694035432389/024e62f7bb8bb5a49901622b43fd044aedc49025?sender=u8174af0a23de37cd1e842670

**Comment by akallish** [comment]
Hello @katenamgayoung, @bhavanisp

Good Morning.

What is the status of this task?

- Remember any team member can move this task from "new issue" to "in progress" on the team kanban. 
- You also create a check box list if a team member has completed a task (besides having conversations about the task) like below:

- [ ] Gayoung Nam 
- [x] Bhavani Shivaram Prasad 
- [ ] Rutuja Chavan Vasant

You can also have conversations, add links, and add images to an issue to help complete a task.

**Comment by akallish** [comment]
Hello @crutuja. You should see this post. Please reply.

**Comment by bhavanisp** [comment]
Hello @katenamgayoung @crutuja I have moved this issue to inProgress
