### ISSUE TITLE
Out of Class Work : Teams to choose an ID project to focus on

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team2#3]
@katenamgayoung, @bhavanisp

• Each team member should complete the "What I want: Mural asynchronously"
• Upload a PDF of the project they want considered to their GDrive folder
• Meet synchronously to discuss each project, then choose the one that is most mature
• Complete the "What we want" section together
• Delegate roles (the person whose project is chosen is automatically the product manager)

Team 1
https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1694035378749/4d1b5d1ec86e05550714642152084635b93b6423?sender=u8174af0a23de37cd1e842670

Team 2
https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1697552446049/c54c0e9f96d1e9b60846aeb03ae3865b4af5e306?sender=u8174af0a23de37cd1e842670

Team 3
https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1697552604776/f742e92bfe23aa1de14e66122b066204698bc9e3?sender=u8174af0a23de37cd1e842670

Please put chosen project PDF in GDrive folder
https://drive.google.com/drive/folders/1wqix1Urp6r404wTBg2QQPDcjbqD1pVrZ?usp=drive_link

**Comment by akallish** [comment]
Hello @katenamgayoung, @bhavanisp

Good Morning.

What is the status of this task?

- Remember any team member can move this task from "new issue" to "in progress" on the team kanban. 
- You also create a check box list if a team member has completed a task (besides having conversations about the task) like below:

- [ ] Gayoung Nam 
- [x] Bhavani Shivaram Prasad 
- [ ] Rutuja Chavan Vasant

You can also have conversations, add links, and add images to an issue to help complete a task.

**Comment by akallish** [comment]
Hello @crutuja . You should see this post. Please reply.

**Comment by akallish** [comment]
Each team should post their chosen project on GDrive no later than mid-day on Tuesday so I can review them in time to discuss the chosen project to each team on Wednesday.

**Comment by bhavanisp** [comment]
PDF uploaded and Choosing ID project mural updated.

**Comment by akallish** [comment]
> PDF uploaded and Choosing ID project mural updated.
> 
> 

@bhavanisp thanks for the update

**Comment by katenamgayoung** [comment]
Completed uploading the chosen project on GDrive.

**Comment by akallish** [comment]
@katenamgayoung, @bhavanisp, @crutuja just visited your project sandbox but only see one project and no other content. Was hoping to review the chosen project and learn what questions and assumptions the team has. We can talk tomorrow morning.
