### ISSUE TITLE
Out of Class Work : Review week 01 Team to choose meeting times and publish to team Google Calendar

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team2#5]
@katenamgayoung, @bhavanisp

This is the calendar for Team One. It should be used for listing synchronous meeting times.

Each team is to agree on the following weekly synchronous meetings :
• 1 60 minute meeting (placeholder in team calendar)
• 1 30 minute meeting (placeholder in team calendar)
• Weekly 1 hour windows for quick and targeted 15 minute meetings (time windows in team calendar)

These meetings can move and change as one offs when needed. 

Each formal meeting should have an agenda :
• purpose of meeting
• pre-work for meeting
• issues to be discussed at meeting
• exit goals of meeting
Team members do not have to attend a formal meeting without an agenda.

Class Calendar
https://calendar.google.com/calendar/u/0?cid=Y185NDI2N2YzYTIyOTIzZWIzZDdmYTI1NTM5YzkxYjgyNWRkNjYyMzBhYzU1ODhhZGQ1ZTNkZGZkMmMzY2VlMGViQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

Team 01 Calendar
https://calendar.google.com/calendar/u/0?cid=Y18zYzJmYjc3Y2U3ODgwN2E3MDc4NTM0NzZlYjgwNTE5ZTBiNTgxZDg5N2FiNDJlNWJiNDUwM2QyZjQ5NjFiMTNhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

Team 02 Calendar
https://calendar.google.com/calendar/u/0?cid=Y19jNmU5ZTBmZDhlYTc5ZDBmZjY2NGRiODQ5YTJlMWFiNGVjOWM5NjVmNmQ1ODIyM2I0ODE3OGQ3OTNiM2Y1YzE1QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

Team 03 Calendar
https://calendar.google.com/calendar/u/0?cid=Y18zODg0OGFlOTRlNmVhY2Q3NTAyMDE5Zjk0M2Q4NjI1OWU2YjFkYWNjMzY0YmY4NDA5NTM4ZjMwNTVlY2YxMTc2QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

**Comment by akallish** [comment]
Hello @katenamgayoung, @bhavanisp

Good Morning.

What is the status of this task?

- Remember any team member can move this task from "new issue" to "in progress" on the team kanban. 
- You also create a check box list if a team member has completed a task (besides having conversations about the task) like below:

- [ ] Gayoung Nam 
- [ ] Bhavani Shivaram Prasad 
- [ ] Rutuja Chavan Vasant

You can also have conversations, add links, and add images to an issue to help complete a task.

**Comment by akallish** [comment]
Hello @crutuja . You should see this post. Please reply.

**Comment by akallish** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmxpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--888c950ccd15afe4cedbc7c977363c39bba9dc44/Screenshot%202023-10-23%20at%201.58.54%E2%80%AFPM.jpg)

Each team has their own google team calendar. Here is a cheat sheet to create and post invitations for your team meetings:
https://support.google.com/calendar/thread/12002803/how-to-create-an-event-to-a-specific-calendar?hl=en

**Comment by akallish** [comment]
@katenamgayoung, @bhavanisp, @crutuja If you can post on Google Calendar the weekly scheduled meeting times and windows for 1 hour, 1/2 hour and 15 minute slots. Thanks.

**Comment by akallish** [comment]
I received your Google Calendar invitations. Thank you.

**Comment by bhavanisp** [comment]
@katenamgayoung @crutuja I shall move this issue to closed? As we are done reviewing this.
